### PR TITLE
WIP: Appraisalbuilder

### PR DESCRIPTION
**Pull request by sbillinge**
@scopatz  I wasn't going to add this because it was somewhat Columbia specific, but it is a builder for annual appraisal (answering the questions we have at Columbia).  However, I think it is valuable in general, and it has some updates to the schema that I would like to reuse in other developments, so I think I would like to consider merging it.

I will need to do some work to clean it so it passes tests etc., but will get back to you when I am ready.  Feel free to review at any time and give feedback.

### CODE REVIEW

**Comment by scopatz** [comment]
No problem having institution specific code! Feel free to ping when needed

**Comment by sbillinge** [comment]
@CJ-Wright could you have quick look at the failing test for the ann-appraisal builder.  It looks to me that the render command is not writing the tex file but I can't figure out why.

**Comment by sbillinge** [comment]
btw, fixing the schema is still WIP, though I think the EXEMPLAR should be ok.

**Comment by scopatz** [comment]
Looks like there is a test failure

**Comment by scopatz** [comment]
And now a conflict with master

**Comment by sbillinge** [comment]
yes, @scopatz still struggling with this one.  Trying to find time  to
finish it....

**Comment by scopatz** [comment]
Ok!

**Comment by sbillinge** [comment]
@mwinitch I hate to do this to you, but I really need help to get this merged.  It has some major functionality in it and schema work that is needed for other projects.  Here are the tasks that I think it needs to be merged:

- [ ] fix the date logic so it properly uses your new date logic!

- [ ] make it pass tests.  It was just failing validate inside the tests, where the schema validates against the database built from the exemplars.  this is hard to debug because there is a sys.exit that catches the error without dumping the stack.  It will take some fiddling around!  What in the exemplar is not validating in the schema.  I think it is in the grants collection but not sure, and there may be more validation fails

- [ ] change the name.  I think the builder, and all the stuff around it like the template and output filenames etc. should be called something like activity_summary instead of annual_appraisal.

- [ ] make sure there are no hard-coded things in there. When I first wrote it it just built for sbillinge.  I htink I fixed that but look for anything else that looks like that.

That's all I can think of right now.

btw, to access it, fork my fork and do hte normal workflow, making my fork upstream.  We can chat if it helps

**Comment by sbillinge** [comment]
moved to #408

**Pull request closed without merging**
