### PR TITLE
Fixing issue breaking u_milestone

### PR DESCRIPTION
**Pull request by connorjbracy**
Closes [Issue #790](https://github.com/regro/regolith/issues/790#issue-940942427)

### CODE REVIEW

**Comment by sbillinge** [comment]
do you know what the "identifier" and pop are trying to accomplish?  It is hard to fix without knowing that.  git blame suggests that it was code inserted by zach.

**Comment by sbillinge** [comment]
@connorjbracy I almost have a fix for this.  If it passes tests I will throw it into a PR and close this one.

**Comment by connorjbracy** [comment]
> 
> 
> do you know what the "identifier" and pop are trying to accomplish? It is hard to fix without knowing that. git blame suggests that it was code inserted by zach.

The line that I put into a `for...loop` was indeed added by Zach, but he did not "invent" the line. Given that it is not clear in-line why we want to delete `'identifier'`, I had hopped into a call with Zach last night before making the edit to see if he knew but it was also not clear to him. Although he is not sure why that logic is there in the first place, his motivation for making the change was that, in setting up mongoDB, he noticed there were times when a `pdoc['milestone']` dictionary did not have an `'identifier'` key, thus he changed the previous deletion method to a more safe one (although he also added a new delete line)

The edit(s) he made which introduced the line causing the error that opened [Issue #790](https://github.com/regro/regolith/issues/790#issue-940942427) can be seen in [PR #788](https://github.com/regro/regolith/commit/9a142ed512dd82b2a5cbce2ce04fd25a63b11c0a) which shows the edit to a safer delete on line 274-275 in `regolith/helpers/u_milestonehelper.py`, as well as adding a corresponding line at line 272 (which is the line causing the error that opened [Issue #790](https://github.com/regro/regolith/issues/790#issue-940942427)). The problem with the erroring line is that it is attempting to do the same thing of deleting `'identifier'` from a `'milestone'` dictionary, but here it's targeting _milestones_ within in `pdoc` (i.e., a list of milestone dictionaries) which results in line 272 effectively doing `list({'milestone': ...}).pop('identifier', None)` so I simply wrapped this in a loop to properly delete 'identifier' from each 'milestone' dictionary.

**Comment by connorjbracy** [comment]
It appears that deleting the additional (incorrect) `.pop(...)` line (272) altogether fixed the issue (at least, as far as the pytests are concerned), although I'm not sure if this line is indeed needed for the work in getting mongoDB to work or not.

**Comment by connorjbracy** [comment]
For previous commit, diffed with `upstream/master` without fetching so I did not catch some edits that had been made since the initial branch which resulted in the previous commit's code coverage errors. This has been remedied by fetching, pulling, and merging `upstream/master` into this branch.

**Comment by sbillinge** [comment]
ok, it took me way too long to figure this one out, but the problem was a missing `deepcopy ` when we first created the `all_milestones` list.  I then had to fix all the fixes scattered through the code coming from this error, some of which had been baked into the tests.  I then did a bit more cleaning and increased test coverage just a bit, so the code emerges better!!!! 

I will close this PR.  The issue is closed by the other merged PR.    

Thanks for your work on this.....

**Pull request closed without merging**
