### PR TITLE
Move all the date filters to the dates.py which may be a better place for them

### PR DESCRIPTION
**Pull request by sbillinge**
@scopatz this is a WIP.  Needs tests and all kinds of things.

### CODE REVIEW

**Comment by sbillinge** [comment]
Note to self, still needs tests

**Comment by sbillinge** [comment]
@scopatz this should be ready to merge now

**Comment by sbillinge** [comment]
whoops, forgot to remove the WIP from the title. @scopatz this should be ready for merge now

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
