### PR TITLE
WIP: Closes Issue 919 - Testing helpers results in errors on freshly cloned master branch: 'xonsh.lib.subprocess' has no attribute 'CalledProcessError`

### LINKED ISSUE #919: Testing helpers results in errors on freshly cloned master branch: 'xonsh.lib.subprocess' has no attribute 'CalledProcessError`
Whenever I `run python run_tests.py tests/test_helpers.py`, I get 92 of these errors:
`AttributeError: module 'xonsh.lib.subprocess' has no attribute 'CalledProcessError`

### PR DESCRIPTION
**Pull request by N-G-Asker**
closes #919

### CODE REVIEW

**Comment by N-G-Asker** [comment]
This is my first stab at correcting the issue. Review/input from @connorjbracy and others with system background needed before next iteration

**Review by sbillinge — CHANGES_REQUESTED** [review]
Thanks, I see what you are doing there.   One suggestion...you are now fixing two bugs on the same branch which is often not a good idea.  I would suggest to move the subprocess edits to a new branch that is checked out on a clean default branch and fix these separately.  To make it more readable maybe call it `xonsh_subprocess` instead of `sub_process`?

Do we know what changed from xonsh 0.11 to 0.12 that caused this to break?  It may be worth asking over at xonsh

**Comment by sbillinge** [comment]
btw, I pulled this to my local and ran tests in my env (xonsh 0.11) and it passed the `validate_python_bad` test (still more work to get it to pass the hm8 and hm91 tests)

**Comment by N-G-Asker** [comment]
Thanks for feedback and guidance on the morning call. Closing this PR in favor of PR #921 just created.

**Pull request closed without merging**
