### PR TITLE
Lazy DBs for builders

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@scopatz ready for review!

**Comment by CJ-Wright** [comment]
@sbillinge if you could give this a shot it would be great! I'm implemented it for the CV builder

**Comment by sbillinge** [comment]
Thanks for this CJ!

I tested it with manuscriptreviewbuilder and it didn't seem to work.  When
``needed_dbs`` was not specified every collection was loaded and all built
fine, but when ``needed_dbs = ['refereeReports']`` was specified it ran
with no errors, but nothing was built.

**Comment by CJ-Wright** [comment]
@sbillinge it seems that we aren't testing the manuscipt reviewer? Would it be possible to update the tests to cover those builders?

@scopatz can we add codecov to this?

**Comment by sbillinge** [comment]
Haha, you got me. That was on the list for after I got appraisalbuilder
passing.  I need to be testing postdocadvbuilder and proposalreviewbuikder
(and possibly others too)...also on my list.

S

**Comment by scopatz** [comment]
This looks good!

**Pull request merged**
