### PR TITLE
resolving regolith issue 904

### PR DESCRIPTION
**Pull request by EasterJaylah**
Modified a_projectumhelper.py to create function to automatically generate Google Doc in 'bg-projects' Google drive for new prums.

### CODE REVIEW

**Comment by sbillinge** [comment]
This is a great start, thanks @EasterJaylah .  I think you figured it out but we can never store credentials in a GH repository, especially a public one like regolith,  because it gives everyone in the whole world access to our google drive.  Updating with commit that deletes it doesn't remove the credentials because git stores diffs (changes) so the whole history is there forever and we can always find it.  This means that we need to delete this whole branch from this account (where it appears as a PR branch, I will do that), your fork, and your local.    Save your edits to a file somewhere outside of git territory (like your local login directory, then use `git branch -D branchname` and also  make sure to delete it from your fork.  

When this is done, create a brand new branch built off a sync'ed main, and if you like you can copy-paste the code you have saved in your login directory (but don't save and copy those credentials or coures) into that branch.  I have a bunch more comments, but if I put them here, when I kill this branch they will be lost. So I will put them there when you have done that.

**Comment by sbillinge** [comment]
one more thing.  Please use a more informational title for your PR (I can't remember what issue 904 is). THe best way to do it is to give the informational title, then in the comment below put "Closes #904".  In that way, when the PR is merged, that issue will automatically be closed with a reference to the PR that closed it.

**Comment by sbillinge** [comment]
wait, you are up?  Shouldn't you be sleeping?

On Sun, Jun 19, 2022 at 8:46 AM EasterJaylah ***@***.***>
wrote:

> Closed #932
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_regro_regolith_pull_932&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=bRaj-jRyJHvK5fLXHoYS1z8v5FQJsUhHsWULYh-MrT8VNkoD-RfJhO6JlcyJh0Ni&s=8_HgZ45cqUeRYkXp4evBtBOnx32xE0gMOP0Ge-8Namc&e=>
> .
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_regro_regolith_pull_932-23event-2D6834342439&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=bRaj-jRyJHvK5fLXHoYS1z8v5FQJsUhHsWULYh-MrT8VNkoD-RfJhO6JlcyJh0Ni&s=AvOqLxqFnRuexO4jaXK9KNF3eOMMb6J5ZPo8f-Krzq0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABAOWULW6LQDN3YHIXEVKXTVP263HANCNFSM5ZFYDPCA&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=bRaj-jRyJHvK5fLXHoYS1z8v5FQJsUhHsWULYh-MrT8VNkoD-RfJhO6JlcyJh0Ni&s=FCZPKaGl4-KoozRMgjEMYD-GwdTKH8ID5FeShZbTb3U&e=>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>


-- 
Simon Billinge
Professor, Columbia University
Physicist, Brookhaven National Laboratory

**Comment by EasterJaylah** [comment]
Haha, I think I have officially encountered my first “rabbit hole”. This is
actually all a fever dream. :)--
Jaylah Easter (he/they)
UMES Engineering ‘23
Henson Entrepreneur Endowed Honors Scholar
LSAMP Research Scholar
Undergraduate Teaching Assistant

-- 
CONFIDENTIALITY NOTICE: This message may contain confidential information 
intended only for the use of the person named above and may contain 
communication protected by law. If you have received this message in error, 
you are hereby notified that any dissemination, distribution, copying or 
other use of this message may be prohibited and you are requested to delete 
and destroy all copies of the email, and to notify the sender immediately 
at his/her electronic mail.

**Comment by sbillinge** [comment]
oh no!

I am having a meeting with Kayla today at 12pm ET on a similar issue she is
facing, but more importantly how to approach problems using a test driven
development approach (which is one of hte best ways to avoid rabbit
holes).  If you can get some sleep now so you can make that call, I
normally don't want you working on the weekend unless you want to (work
life balance), but it could save me time if I only have to go through it
once....

S

On Sun, Jun 19, 2022 at 8:56 AM EasterJaylah ***@***.***>
wrote:

> Haha, I think I have officially encountered my first “rabbit hole”. This is
> actually all a fever dream. :)--
> Jaylah Easter (he/they)
> UMES Engineering ‘23
> Henson Entrepreneur Endowed Honors Scholar
> LSAMP Research Scholar
> Undergraduate Teaching Assistant
>
> --
> CONFIDENTIALITY NOTICE: This message may contain confidential information
> intended only for the use of the person named above and may contain
> communication protected by law. If you have received this message in
> error,
> you are hereby notified that any dissemination, distribution, copying or
> other use of this message may be prohibited and you are requested to
> delete
> and destroy all copies of the email, and to notify the sender immediately
> at his/her electronic mail.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_regro_regolith_pull_932-23issuecomment-2D1159632682&d=DwMFaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=buQKdqlwWmCexaU4XknOGazVnWP3noVz9uDAitSPAiTc5qAJi2DvY1YjrW9Q0UIc&s=lYKpcklIsiQjyPe2FvTk8t698Na9nDelVtFw0QLMn5s&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABAOWUN2SCXVVC6QXENXJ6DVP3ACJANCNFSM5ZFYDPCA&d=DwMFaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=buQKdqlwWmCexaU4XknOGazVnWP3noVz9uDAitSPAiTc5qAJi2DvY1YjrW9Q0UIc&s=DJepniHMhvK6Yz-jutaJ2NfsCww-8HM2RLqjTs1Viys&e=>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>


-- 
Simon Billinge
Professor, Columbia University
Physicist, Brookhaven National Laboratory

**Pull request closed without merging**
