### PR TITLE
u_milestonehelper.py: removed functionality that allowed the user to …

### LINKED ISSUE #1009: u_milestone "success" message printed after database update
- [ ] line 275 of u_milestoneupdater.py: change print statement into a string variable and have this variable update an empty list. the empty list variable will be used to store a list of all the strings that will be printed .
- [ ] add print statement that prints the list of strings after the database is dumped. this is needed because we only want to notify the user of their successful updates _after_  the db has been updated.

### PR DESCRIPTION
**Pull request by dpeters001**
…input multuple ms uuids. Fixed the problem of having a mix of success and failure messages. test_helper.py: u_milestone tests updated to reflect diminished functionality. only one uuid is tested at a time.

Closes #1009
@dpeters001  if you add this closes statement here (see above, I did it) the relevant issue will automatically close when the  PR merges.

### CODE REVIEW

**Comment by dpeters001** [comment]
@sbillinge when you get a chance please check out my last two commits. I made commit (235f24b) without syncing my branch `u_milestone_rm_loop` to your commit (e5510a8). I rebased the branch in order to push my commits. Does that make sense? I have no problem starting over if this will be an issue.

**Comment by sbillinge** [comment]
@dpeters001 please kill this and do a new branch, because the structure has changed high up in the code it is better to start over, but I think the changes may only be a few lines at this point.  We could even leave in the multiple uuids actually with this behavior:

> 1) try and find the uuids in the current db
> 2) if they are all found, go for it
> 3) if some are found, do the ones that are found and let the user know that `[these]` were done but `[these]` were not found, maybe they are in a different database than the one specified?
> 4) if none were found, message that none were found, maybe in a different db

I think this will work nicely actually.

**Comment by dpeters001** [comment]
@sbillinge seems that some of the tests in test/test_validate.py are failing.

**Comment by dpeters001** [comment]
> @dpeters001 please kill this and do a new branch, because the structure has changed high up in the code it is better to start over, but I think the changes may only be a few lines at this point. We could even leave in the multiple uuids actually with this behavior:
> 
> > 1. try and find the uuids in the current db
> > 2. if they are all found, go for it
> > 3. if some are found, do the ones that are found and let the user know that `[these]` were done but `[these]` were not found, maybe they are in a different database than the one specified?
> > 4. if none were found, message that none were found, maybe in a different db
> 
> I think this will work nicely actually.

Will do!

**Pull request closed without merging**
