### PR TITLE
WIP: moving method for finding group members to tools

### PR DESCRIPTION
**Pull request by sbillinge**
everything is working, except @CJ-Wright I can't figure out how to write the tests.....the function is normally handed a list of ChainedDB objects and I am struggling to mock that.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
I guess you could load the conftest DB and then pull records from that?

**Comment by sbillinge** [comment]
Right, need help with that....

**Comment by sbillinge** [comment]
This seems to have a nasty merge of upstream somewhere along the line.  I think I will close this and put the new functionality on a new PR.

**Comment by sbillinge** [comment]
replaced by #319

**Pull request closed without merging**
