### PR TITLE
Cookie into main

### PR DESCRIPTION
**Pull request by sbillinge**

### CODE REVIEW

**Comment by bobleesj** [comment]
@sbillinge nice codecov is configured.. for `codecov/patch` since the % is calculated for the chnages in this PR and `conftest.py` isn't fully covered (makes sense...) it's failing here.

**Comment by sbillinge** [comment]
NOTE: please sync your main and next round of cleaning will be directly into main.

**Comment by bobleesj** [comment]
noted

**Comment by bobleesj** [comment]
> @tinatn29 @bobleesj great news.....cookie is merged into main on roglith passing all tests!  Great job!!!!  138 files modified, and years of technical debt.   Plenty more to clean up, but this is a HUGE milestone.  Thanks!  I will try and build my cv etc. from the new main and let you know how that goes....

Keep us posted! Automatic CV generation sounds very nice.

**Comment by sbillinge** [comment]
the cv built fine, my todo list built fine, publication list built, preslist built.  I didn't test everything, but long story short, the cookie cutting seems to have been accopmplished without any major breakage!!!! and at least for my "in production" use of regolith in devleop mode, it is working great!

**Comment by sbillinge** [comment]
> > @tinatn29 @bobleesj great news.....cookie is merged into main on roglith passing all tests!  Great job!!!!  138 files modified, and years of technical debt.   Plenty more to clean up, but this is a HUGE milestone.  Thanks!  I will try and build my cv etc. from the new main and let you know how that goes....
> 
> Keep us posted! Automatic CV generation sounds very nice.

yes, @bobleesj @tinatn29  let's get you all regolithified!  I can build the cv for everyone in the group, you just need all the info in databases!  If you like we can have a hackathon in the new year.   Then when you have your own groups you can migrate and build everything for all your group members.  I will share my cv to slack and you can see what it looks like.

**Comment by bobleesj** [comment]
I am interested! (Taking our convo to Slack)

**Pull request merged**
