### PR TITLE
Little bit of schema cleaning in Institutions

### PR DESCRIPTION
**Pull request by sbillinge**
WIP please wait to review

### CODE REVIEW

**Comment by scopatz** [comment]
Just let us know when it is ready for review!

**Comment by sbillinge** [comment]
@CJ-Wright one thing I would like is a conditional validation on 'state' such that it is required when 'country' is 'USA' but not required otherwise.  Right now it is failing validation when it finds a 'state' field when 'country' is not 'USA'

**Comment by CJ-Wright** [comment]
I can try to get that to work, I think there was another case like that too (with seminar type and department).

**Comment by sbillinge** [comment]
@CJ-Wright it already has a conditional validation, but it seems to be not quite working as desired.  We somehow want the condition on whether or not the field is required, rather than whether or not it is present.  I have no idea how one would do it, but I think this will be a more common situation so would be super-userful to figure out.....

**Comment by sbillinge** [comment]
it looks as if something like this could work:
```
import cerberus

v = cerberus.Validator()
schema1 = {"type": {"required": True, "allowed": ["folder"]}, "layer": {"required": True}}
schema2 = {"type": {"required": True, "allowed": ["category"]}}

schema = {"oneof": [schema1, schema2]}
doc = {"type": "folder", "layer": "a"}
v = Validator(schema)
v.validate(doc)
print v.errors
```
I will try it.

**Comment by sbillinge** [comment]
@CJ-Wright @scopatz this is ready for review.  I either need help with the ``!= USA`` within a dependency, or we could pull this in, since it is working, but create a new issue for the better not equal logic that I want.

**Comment by sbillinge** [comment]
@scopatz this should be ready to merge now.  I want to start working on the group web-page, which won't build without this merge, and another one to follow with small schema tweaks in people.  Thanks so much.

**Comment by scopatz** [comment]
thanks again!

**Pull request merged**
