### PR TITLE
fix open

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
As soon as the CI is done I'll merge. Thank you @scopatz for the review!

**Comment by CJ-Wright** [comment]
I guess ruamel got updated, yey!

**Comment by CJ-Wright** [comment]
Can we/is there a good way to turn the loaded yaml back into base types?

**Comment by scopatz** [comment]
`p.get("aka", [])` probably needs to be `list(p.get("aka", []))`

**Comment by CJ-Wright** [comment]
yes but then I get `AttributeError: 'CommentedSeq' object has no attribute 'sort'`

**Comment by scopatz** [comment]
what about `[x for x in p.get("aka", [])]`

**Comment by CJ-Wright** [comment]
Sorry I should have been more explicit, that works for that line, but then we get further issues from yaml where the types aren't right. My sort comment was for education. I'll patch things as I can but if I need to put in more than ~5 I might look at some sort of recursive re-typing on yaml load.

**Comment by CJ-Wright** [comment]
@scopatz ready for another round!

**Comment by scopatz** [comment]
Thanks! Given this change, we probably want a hotfix release

**Comment by CJ-Wright** [comment]
Thank you! Will do

**Pull request merged**
