### PR TITLE
collect appointments function

### PR DESCRIPTION
**Pull request by adibaejaz**
please see my collect appointments function (presently for use in grant burn function)!

### CODE REVIEW

**Comment by adibaejaz** [comment]
also @sbillinge  @jc-umana this might be useful in the appointments by grant lister as well! by running 
`appts = collect_appts(self.gtx['people'], 'grant', rc.grant, None, None)`
and printing each element of `appts,` the job is pretty much done!

**Comment by adibaejaz** [comment]
@sbillinge hahah thank you Professor! l am slowly getting the hang of it, and quite enjoying thinking of edge cases for these tests! I have added a news, and this is ready for final review

**Comment by sbillinge** [comment]
you can see how the tests make the code much better.  Not only do the tests test, they force you to think more deeply about your code and come up with better designs, right?

**Comment by adibaejaz** [comment]
they certainly do!

**Pull request merged**
