### PR TITLE
adding a whitespace

### PR DESCRIPTION
**Pull request by pliu2781**
Let's see if this passes on travis

### CODE REVIEW

**Comment by pliu2781** [comment]
This branch also has the same travis error

**Comment by sbillinge** [comment]
ok, I will run the same travis test from my fork....

**Comment by sbillinge** [comment]
this failed for me too.  We will have to track down why this is failing.  It seems that an assert is looking for "Errors found in " and gets back "".  We need to track down what module or package prints "Errors found in " and why it is not longer printing it, even though it seems to be there in the stdout that is captured in the test.

**Comment by pliu2781** [comment]
Maybe Travis is using the wrong subprocess library? test_validate.py is using the xonsh.lib subprocess library.

**Comment by sbillinge** [comment]
Hi @pliu2781 I am afraid we may need to get some help from Zach/Connor on this.  Can you reach out to them?   My best guess i that how the errors are passed back from the validators is changing with either a change in Cerberus (the json validation code we use) or a python version bump).  To recreate the bug we could try making a new local environment that is using the same version of python and cerberus as Travis is.   I am not sure to find out what Travis is using, but try making a new environment using the latest python and the latest cerberus.... That is my best suggestion at this point, but we really need it passing again....

**Pull request closed without merging**
