### PR TITLE
FIX: month to int now properly handled

### PR DESCRIPTION
**Pull request by sbillinge**
@scopatz this is a bug fix PR

### CODE REVIEW

**Comment by sbillinge** [comment]
What does this mean? A bad database entry that causes it to crash?

**Comment by CJ-Wright** [comment]
I would modify the exemplars so that the prior code tests would have failed, while the fix in the PR causes the test to pass.

**Comment by sbillinge** [comment]
Ah gotcha

**Comment by CJ-Wright** [comment]
It might not be truly needed for a simple bug fix like this, but it is good practice to make certain that the bug a PR is supposed to squash is the correct one and that we don't have the bug crop up again.

**Comment by sbillinge** [comment]
OK, @CJ-Wright I checked and this new schema fails tests without the fix

**Comment by CJ-Wright** [comment]
Thank you very much! LGTM

**Pull request merged**
