### PR TITLE
Fix dots

### LINKED ISSUE #225: Too many dots in CV/Resume
Some of my service/award entries are long and they cause the dates to drop off the page.

### PR DESCRIPTION
**Pull request by CJ-Wright**
Closes #225

### CODE REVIEW

**Comment by scopatz** [comment]
Seems fine to me.  CI fails though

**Comment by CJ-Wright** [comment]
I need to update the tests to use the latex code, but I didn't want to make the change until we were happy with the outcome.

**Comment by scopatz** [comment]
CI is still failing :(

**Comment by CJ-Wright** [comment]
ping

**Comment by scopatz** [comment]
Waiting on #231 for this.

**Pull request merged**
