### PR TITLE
Enum pos

### LINKED ISSUE #117: enum positions for people
This way we can have one source of truth.

### PR DESCRIPTION
**Pull request by CJ-Wright**
closes #117

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@scopatz ready for review!

**Comment by scopatz** [comment]
Is this backwards compatible?

**Comment by CJ-Wright** [comment]
I think it should be, what did we do if a position was not in the sorter dict?

**Comment by CJ-Wright** [comment]
Ah I see the problem we defaulted the lookup to `''`. Do you want to run a dep cycle?

**Comment by CJ-Wright** [comment]
I guess one could make an argument that they are already broken and we're just being silent about it. It would be nice if we could enter this into the schema but not have it enforced so it would show up in the docs but not be validated against.

**Comment by CJ-Wright** [comment]
@scopatz I think this is ready for another look!

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
