### PR TITLE
black

### PR DESCRIPTION
**Pull request by CJ-Wright**
reformatting of the code using black (in advance of xonsh-ification since we don't have auto-format for that yet)

### CODE REVIEW

**Comment by CJ-Wright** [comment]
This should most likely be merged after #172 so the mega merge conflicts are on my side :wink:

**Comment by scopatz** [comment]
Thanks!  I was leaving #172 up to you!

**Comment by scopatz** [comment]
This has some expected conflicts now.

**Comment by CJ-Wright** [comment]
Yea I might just re do this from master.

**Comment by CJ-Wright** [comment]
Closing in preference of black 2.

**Pull request closed without merging**
