### PR TITLE
added utf8 input encoding to the latex templates

### LINKED ISSUE #233: fix utf8 in presentation list builder
I built preslists recently and I saw an a with an umlaut in the db that didn't render.  Need to look into this at some point.

### PR DESCRIPTION
**Pull request by sbillinge**
closes #233

@scopatz this should be ready for review.  It allows us to store utf8 in the database and still have the latex build.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
You need to update the expected outputs to include the utf8 line.

**Comment by sbillinge** [comment]
right.  I was thinking about how to test this last night.  I think I need
some utf8 characters in the exemplar schema also, right?

**Comment by CJ-Wright** [comment]
Maybe? We don't compile the test examples.

**Comment by sbillinge** [comment]
I see, you just create files and write stuff in there and see if it is the
same as the outputs files?  The real test is if the latex compiles with the
UTF8 or not, but I don't think we want latex compilation happening during
unit testing, and it is easy to catch that bug when it happens.....

**Comment by CJ-Wright** [comment]
Yes

**Comment by sbillinge** [comment]
@CJ-Wright  @scopatz not sure whey these tests are failing...they are on files I haven't touched.  It looks like some incompatibility on the last line of the built file ``\end{document}`` but I don't see any missing or added carriage returns or spaces.  These tests pass when I run these tests on windows,  ironically....

**Comment by sbillinge** [comment]
OK, @scopatz @CJ-Wright  I think I need some help here.  I have no idea why these are failing, or why the outputs files think I have changed the ``\end{document}`` statement (which I didn't) and why the templates documents (on the whole) don't think I changed that line.....

**Comment by sbillinge** [comment]
I will rebase this onto master after #258 is merged and it should pass tests at that time and we can merge this one too.  I would rather do it this way than make it pass and introduce conflicts.

**Comment by sbillinge** [comment]
@scopatz @CJ-Wright This should be ready to merge now also.

Working towards getting our html to build without errors.  I think we are close now.

**Comment by scopatz** [comment]
Thanks!

**Comment by sbillinge** [comment]
Thanks for merging!

**Pull request merged**
