### PR TITLE
cherry picking commits from other issue#814 PR

### PR DESCRIPTION
**Pull request by pliu2781**

### CODE REVIEW

**Comment by pliu2781** [comment]
For some reason, travis isn't running

**Comment by pliu2781** [comment]
TravisCI says these builds aren't running because: Owner regro does not have enough credits.

**Comment by sbillinge** [comment]
OK, thanks.  I guess we just have to wait for credits to renew.

**Comment by pliu2781** [comment]
When credits renew, I will try to do this cherry pick process again on a new PR

**Pull request closed without merging**
