### PR TITLE
Notes for regolith mongo projecta

### PR DESCRIPTION
**Pull request by dpeters001**
Creates a subdirectory for regolith notes and adds the dp_regolith_prums_to_mongodb.md notes to the subdirectory. These notes detail the code modifications that were made to diagnose the causes of the regolith latency issues on the fs and mongodb backends.

### CODE REVIEW

**Comment by sbillinge** [comment]
Hi Dom,

I am a bit nervous about this PR now, it seems to have many new commits on it that are coming from multiple other merges of the code by other people.  It looks as if a rebase or a merge went wrong.   The best may be to make a new branch that has your edits on it but not all the other stuff.  Is there a reason you did a merge/rebase?  I didn't see that it had any conflicts on the previous version of teh PR?

**Comment by dpeters001** [comment]
Hey Simon,

I see what you mean. I pulled from the master prior to creating this branch so it has all of the most recent updates. I put the PR in for the ```regro:pymongo``` branch because I thought we were going push to that branch until we were ready to fully integrate the mongodb backend. The notes are probably a good update for the ```regro:master``` branch anyways. I will close this PR, make a new branch on my end, and put in a PR for the ```regro:master``` branch.

**Comment by sbillinge** [comment]
Maybe I got confused and this should stay on the pymongo branch but without
updating from master?

**Comment by sbillinge** [comment]
BTW, please call the docs subdirectory developer_notes to keep it clear

**Pull request closed without merging**
