### PR TITLE
CI: flake8

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by scopatz** [comment]
CI Failing, do we care?

**Comment by CJ-Wright** [comment]
Not too much. It is just flake8, I could move it to the after part, so we don't keep screwing up the docs. Then when we sort out the flake8 stuff we can move it in so that we maintain in the pep8 good graces.

**Comment by scopatz** [comment]
Ok, well, free to merge then.

**Comment by CJ-Wright** [comment]
cycle for ci

**Comment by CJ-Wright** [comment]
Pending CI (since we moved the repo and everything)

**Comment by scopatz** [comment]
Mind if we close this @CJ-Wright?

**Comment by CJ-Wright** [comment]
Sure, I'll just fix things as I go.

**Pull request closed without merging**
