### PR TITLE
Iss924

### LINKED ISSUE #924: Full automatic unit tests and Travis CI fail, due to issue with CalledProcessError in tests/test_validate.py

### PR DESCRIPTION
**Pull request by N-G-Asker**
closes #924

Local testing confirms this commit resolves the following error message/failure when running `python run_tests.py`

FAILED tests/test_validate.py::test_validate_bad - AttributeError: module 'xonsh.lib.subprocess' has no attribute 'CalledProcessError'

This should also resolve the issue on the Travis CI side of the house.

### CODE REVIEW

**Comment by N-G-Asker** [comment]
Apologies -- I messed up and pushed to master accidentally! Closing this and opening new PR

**Comment by N-G-Asker** [comment]
I don't know why all my commit history got lumped into this PR...but the diff between the upstream master and the most recent commit should resolve issue 924.

**Comment by sbillinge** [comment]
please can you redo on a clean branch?  you may have to blow away your whole local and reclone from your fork (assuming you haven't pushed the broken master to your fork) then synchronize from upstream.

**Comment by sbillinge** [comment]
I need to go to bed now, but wanted CI working on regolith, so I merged the patch myself.  I will close this and you can delete the branch.  You may have to blow away your local and reclone to clean up the merge to master problem I am afraid, but this is why we love git....nothing will be lost if you make sure all your branches (not your master) are pushed to origin.  If master is pushed to origin you may have to blow away the fork....while keeping unmerged work....  Make sure to set up the pre-commit hook to avoid this happening again.

**Comment by N-G-Asker** [comment]
Quick post-mortem on what exactly went wrong yesterday (pieced together based on my git log file and using the bash `history` command) -- mostly for my own sanity:

I accidentally branched from my enhancement dev branch, thinking I was actually branching from master. I had been doing some manual testing in rg-db-public locally for my regolith enhancement. But then, I needed to quickly switch gears to make the patch in that regolith testing file. I verified which branch I was on before checking out a new branch, and it was, correctly, master. I then ensured master was synched. However, I was in the wrong repo...still in rg-db-public, and then proceeded to cd to the new directory -- ../../dev/regolith -- and branched from _there_. Turns out, the active branch there was my dev branch, and not master.

The lessons learned for me are to always be cognizant of which repo I'm in locally, and to slow down a little -- I was rushing to make that patch as quickly as possible!

**Comment by sbillinge** [comment]
slow and steady wins the race in software.....and results in better code.   This is a recurring theme in the group.

**Pull request closed without merging**
