### PR TITLE
fix flake8 test_helpers.py

### LINKED ISSUE #1184: Fix flake8 errors - line too long
### Problem

If you run `pre-commit run --all-files`

```

src/regolith/tests/test_helpers.py:125:116: E501 line too long (122 > 115 characters)
src/regolith/tests/test_helpers.py:136:116: E501 line too long (200 > 115 characters)
src/regolith/tests/test_helpers.py:137:116: E501 line too long (311 > 115 characters)
src/regolith/tests/test_helpers.py:138:116: E501 line too long (316 > 115 characters)
src/regolith/tests/test_helpers.py:139:116: E501 line too long (414 > 115 characters)
src/regolith/tests/test_helpers.py:143:116: E501 line too long (200 > 115 characters)
src/regolith/tests/test_helpers.py:144:116: E501 line too long (311 > 115 characters)
src/regolith/tests/test_helpers.py:145:116: E501 line too long (316 > 115 characters)
src/regolith/tests/test_helpers.py:146:116: E501 line too long (414 > 115 characters)
src/regolith/tests/test_helpers.py:151:116: E501 line too long (201 > 115 characters)
src/regolith/tests/test_helpers.py:153:116: E501 line too long (312 > 115 characters)
src/regolith/tests/test_helpers.py:154:116: E501 line too long (317 > 115 characters)
src/regolith/tests/test_helpers.py:155:116: E501 line too long (415 > 115 characters)
src/regolith/tests/test_helpers.py:159:116: E501 line too long (2603 > 115 characters)
src/regolith/tests/test_helpers.py:160:116: E501 line too long (316 > 115 characters)
src/regolith/tests/test_helpers.py:161:116: E501 line too long (413 > 115 characters)
src/regolith/tests/test_helpers.py:162:116: E501 line too long (344 > 115 characters)
src/regolith/tests/test_helpers.py:166:116: E501 line too long (311 > 115 characters)
src/regolith/tests/test_helpers.py:167:116: E501 line too long (316 > 115 characters)
src/regolith/tests/test_helpers.py:168:116: E501 line too long (414 > 115 characters)
src/regolith/tests/test_helpers.py:172:116: E501 line too long (538 > 115 characters)
src/regolith/tests/test_helpers.py:176:116: E501 line too long (538 > 115 characters)
src/regolith/tests/test_helpers.py:180:116: E501 line too long (311 > 115 characters)
src/regolith/tests/test_helpers.py:181:116: E501 line too long (316 > 115 characters)
src/regolith/tests/test_helpers.py:182:116: E501 line too long (414 > 115 characters)
src/regolith/tests/test_helpers.py:186:116: E501 line too long (285 > 115 characters)
src/regolith/tests/test_helpers.py:190:116: E501 line too long (262 > 115 characters)
src/regolith/tests/test_helpers.py:194:116: E501 line too long (262 > 115 characters)
src/regolith/tests/test_helpers.py:199:116: E501 line too long (206 > 115 characters)
src/regolith/tests/test_helpers.py:203:116: E501 line too long (159 > 115 characters)
src/regolith/tests/test_helpers.py:209:116: E501 line too long (284 > 115 characters)
src/regolith/tests/test_helpers.py:210:116: E501 line too long (244 > 115 characters)
src/regolith/tests/test_helpers.py:211:116: E501 line too long (223 > 115 characters)
src/regolith/tests/test_helpers.py:212:116: E501 line too long (224 > 115 characters)
src/regolith/tests/test_helpers.py:213:116: E501 line too long (262 > 115 characters)
src/regolith/tests/test_helpers.py:374:116: E501 line too long (131 > 115 characters)
src/regolith/tests/test_helpers.py:389:116: E501 line too long (131 > 115 characters)
src/regolith/tests/test_helpers.py:410:116: E501 line too long (131 > 115 characters)
src/regolith/tests/test_helpers.py:431:116: E501 line too long (131 > 115 characters)
src/regolith/tests/test_helpers.py:446:116: E501 line too long (131 > 115 characters)
src/regolith/tests/test_helpers.py:461:116: E501 line too long (129 > 115 characters)
src/regolith/tests/test_helpers.py:502:116: E501 line too long (123 > 115 characters)
src/regolith/tests/test_helpers.py:531:116: E501 line too long (123 > 115 characters)
src/regolith/tests/test_helpers.py:557:116: E501 line too long (123 > 115 characters)
src/regolith/tests/test_helpers.py:574:116: E501 line too long (123 > 115 characters)
src/regolith/tests/test_helpers.py:828:116: E501 line too long (123 > 115 characters)
src/regolith/tests/test_helpers.py:847:116: E501 line too long (119 > 115 characters)
src/regolith/tests/test_helpers.py:899:116: E501 line too long (123 > 115 characters)
src/regolith/tests/test_helpers.py:927:116: E501 line too long (118 > 115 characters)
src/regolith/tests/test_helpers.py:1166:116: E501 line too long (149 > 115 characters)
src/regolith/tests/test_helpers.py:1167:116: E501 line too long (138 > 115 characters)
src/regolith/tests/test_helpers.py:1168:116: E501 line too long (137 > 115 characters)
src/regolith/tests/test_helpers.py:1169:116: E501 line too long (166 > 115 characters)
src/regolith/tests/test_helpers.py:1184:116: E501 line too long (125 > 115 characters)
src/regolith/tests/test_helpers.py:1193:116: E501 line too long (196 > 115 characters)
src/regolith/tests/test_helpers.py:1197:116: E501 line too long (133 > 115 characters)
src/regolith/tests/test_helpers.py:1203:116: E501 line too long (164 > 115 characters)
src/regolith/tests/test_helpers.py:1206:116: E501 line too long (121 > 115 characters)
src/regolith/tests/test_helpers.py:1215:116: E501 line too long (125 > 115 characters)
src/regolith/tests/test_helpers.py:1226:116: E501 line too long (224 > 115 characters)
src/regolith/tests/test_helpers.py:1234:116: E501 line too long (128 > 115 characters)
src/regolith/tests/test_helpers.py:1250:116: E501 line too long (128 > 115 characters)
src/regolith/tests/test_helpers.py:1445:116: E501 line too long (157 > 115 characters)
src/regolith/tests/test_helpers.py:1451:116: E501 line too long (341 > 115 characters)
```

### Proposed solution

Address each

### PR DESCRIPTION
**Pull request by tinatn29**
fix #1184 (lines too long)

### CODE REVIEW

**Comment by bobleesj** [comment]
> fix issue #1184 (lines too long)

Thanks Tina, to automatically close the issue, could you please check the link below?

Ref:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue

**Comment by tinatn29** [comment]
actually it might be better to not merge this one yet? I'm not 100% sure that during this fix I had kept the same amount of trailing spaces, which might make tests (perhaps unnecessary) fail? 

(On a different branch I'm dealing with failing tests right now with Assertion errors, where expected and actual outputs are virtually the same except maybe some spacing differences...)

**Comment by sbillinge** [comment]
OK, I will wait to merge this.

**Comment by sbillinge** [comment]
@tinatn29 please can you give an update on where we are with the cookiecut?  I would like to get the tests passing, but when I checked, they still have not been moved over to `regolith/tests`.  Are there other biggish changes that still need to be done.  

Ideally we would have gotten the tests working before too much of the cookiecutting to avoid having to merge too much stuff with failing tests.  Most of the cookiecutting doesn't break things, but it is just more confidence inspiring if tests are passing after each step of teh cookie cutting rather than waiting until the end....

**Comment by tinatn29** [comment]
I've just fixed the failed tests (when running `pytest` locally). I'll move the tests right after you merge #1198 into `cookie`. Right now the tests show 34 skipped and 57 warnings. I'll fixed these after moving the tests

**Comment by sbillinge** [comment]
I merged #1198 .  Does this PR now need to be closed or merged?  I am nervous updating test outputs

**Comment by tinatn29** [comment]
> > So am I. My vote is we close this without merging and make pre-commit `flake8` ignore `test_helpers.py` so we don't mess up the tests. What do you think @bobleesj?
> 
> Yeah, changing the test output without having CI configured initially is usually a scary idea since we don't know the time it has actually worked. I believe this is a pre-commit problem not `pytest` problem? @tinatn29 is the CI test running now?

If what you mean by CI test is the same thing as running `pytest` locally -- then yes (passing with some skips and warnings)! see new PR #1199. Let's close this one and merge #1199?

**Comment by sbillinge** [comment]
> > > So am I. My vote is we close this without merging and make pre-commit `flake8` ignore `test_helpers.py` so we don't mess up the tests. What do you think @bobleesj?
> > 
> > 
> > Yeah, changing the test output without having CI configured initially is usually a scary idea since we don't know the time it has actually worked. I believe this is a pre-commit problem not `pytest` problem? @tinatn29 is the CI test running now?
> 
> If what you mean by CI test is the same thing as passing when running `pytest` locally -- then yes (tests are passing with some skips and warnings)! see new PR #1199. Let's close this one and merge #1199?

I think that for @bobleesj and I it might be better to work to get the CI working First.  It is good that you have tests passing locally, and if so our CI could be you copy pasting a screenshot of the outcome, but maybe the top priority now is doing the work to get the CI working.  @bobleesj we will run into the gooey issue again here.

**Pull request closed without merging**
