### PR TITLE
MAINT: correct the line 47 of reimb.xlsx

### PR DESCRIPTION
**Pull request by st3107**

### CODE REVIEW

**Comment by st3107** [comment]
@scopatz @sbillinge I correct the template of the reimb. There is a format problem at line 47. Ready to merge.

**Comment by sbillinge** [comment]
Thanks @st3107 .  This seems to be failing a codecov test for some reason.....not sure if you can figure it out....

**Comment by scopatz** [comment]
That doesn't matter so much

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
