### PR TITLE
Fix conflicts recent collabs

### PR DESCRIPTION
**Pull request by st3107**

### CODE REVIEW

**Comment by st3107** [comment]
@sbillinge Hi, Simon. I rebased your the recent_collabs to the uptream/master but I cannot push your remote branch, so I open a new PR here. This PR is to merge rebased recent_collabs branch to upstream/master. If tests pass, we can merge this PR and close the conlfict one.

**Comment by st3107** [comment]
Ready to merge.

**Comment by st3107** [comment]
Hello, @scopatz @sbillinge  . I opened this PR to fix the conflicts in the "Recent collaborators" PR. Could you merge this PR? Thank you. Simon will close "Recent collaborators" PR soon.

**Comment by sbillinge** [comment]
@st3107 I am closing this.  There are still things to fix in the original PR so I will rebase that one, and add the fixes.

**Pull request closed without merging**
