### PR TITLE
WIP: fixing merge_collections

### PR DESCRIPTION
**Pull request by adibaejaz**
fixing merge_collections in tools.py to return correct dates

### CODE REVIEW

**Comment by sbillinge** [comment]
@adibaejaz I need some of the functionality in here but I can't merge it because it is failing tests.  Is there any chance you can work on this a bit and try and get it merged?

**Comment by adibaejaz** [comment]
@sbillinge sure, I will start working on it!

**Comment by adibaejaz** [comment]
@sbillinge I have fixed the error in `get_dates`, but this branch has a lot of errors from other helpers that are causing travis to fail
would it be ok if I merged master into this?

**Comment by sbillinge** [comment]
> 
> 
> @sbillinge I have fixed the error in `get_dates`, but this branch has a lot of errors from other helpers that are causing travis to fail
> would it be ok if I merged master into this?

yes, but do a rebase, not a merge.  There are no conflicts, so it will do a fast forward.  It should be quick and easy.

**Comment by adibaejaz** [comment]
@sbillinge I have made quite a bit of progress on this, but there is one last hitch I've found after some debugging, causing `fs-resume` to fail tests
in `resumebuilder.py`, `proposals = list(all_docs_from_collection(rc.client, "proposals"))` is returning an empty list, although right above, `grants = list(all_docs_from_collection(rc.client, "grants"))` is returning the expected list of grants.
I have been staring at this and can't figure it out, but I will look at it again in the morning!

**Pull request closed without merging**
