### PR TITLE
improve error handling in preslistbuilder

### PR DESCRIPTION
**Pull request by sbillinge**
@scopatz please let me test and clean this first before review.

### CODE REVIEW

**Comment by sbillinge** [comment]
@scopatz this should be ready for review and merge now

**Comment by sbillinge** [comment]
@scopatz please wait....it is failing tests....  I will ping you when it is ready.

**Comment by sbillinge** [comment]
@scopatz this is ready for review and merge.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
